# Install & Import Required Libraries

In [1]:
# 📦 Install necessary libraries
!pip install --upgrade gspread gspread_dataframe google-auth scikit-learn

# 📚 Basic Libraries
import pandas as pd
import numpy as np
import re
import nltk
import string
import matplotlib.pyplot as plt

# 📊 Sklearn Modules
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

# 🔐 Google Colab & Drive
from google.colab import drive
from google.colab import auth
import gspread
from google.auth import default
from gspread_dataframe import set_with_dataframe, get_as_dataframe
from google.colab import files


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.3/212.3 kB 2.6 MB/s eta 0:00:00
  Attempting uninstall: google-auth
    Found existing installation: google-auth 2.38.0
    Uninstalling google-auth-2.38.0:
      Successfully uninstalled google-auth-2.38.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.38.0, but you have google-auth 2.39.0 which is incompatible.


# Mount Google Drive & Authenticate Google Sheets

In [2]:
# Mount Drive
drive.mount('/content/drive')

# Authenticate
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)


Mounted at /content/drive


# Load Data from Google Sheets

In [3]:
# Open your spreadsheet
spreadsheet_name = " sentiment_spreadsheet"  # Make sure there's no extra space
spreadsheet = gc.open(spreadsheet_name)
worksheet = spreadsheet.sheet1

# Load sheet data into DataFrame
df = pd.DataFrame(worksheet.get_all_records())

# Optional preview
print(df.head())


                                          Sentence Sentiment
0  The team did an outstanding job on the project.  Positive
1               I’m so proud of how far I’ve come.  Positive
2        This is the best day I’ve had in a while.  Positive
3            Everything went perfectly as planned.  Positive
4              She has a fantastic sense of humor.  Positive


In [4]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

# Text Preprocessing Function

In [5]:
# Preprocess Function
def preprocess_text(text):
    if isinstance(text, str):
        text = text.lower()
        text = re.sub(r'[^a-z\s]', '', text)
        words = text.split()
        stop_words = set(stopwords.words('english'))
        words = [word for word in words if word not in stop_words]
        return ' '.join(words)
    return ""


# Preprocess Sentiment Data Google Sheet

In [6]:
# Install required packages if not already installed
!pip install --upgrade gspread gspread_dataframe google-auth

# Import libraries
import re
import pandas as pd
import nltk
from nltk.corpus import stopwords
import gspread
from google.auth import default
from gspread_dataframe import set_with_dataframe

# Download NLTK stopwords
nltk.download('stopwords')

# Authenticate with Google Sheets
creds, _ = default()
gc = gspread.authorize(creds)

# Load your Google Spreadsheet
spreadsheet_name = ' sentiment_spreadsheet'  # Changed to your new name
spreadsheet = gc.open(spreadsheet_name)
worksheet = spreadsheet.sheet1

# Load data from the spreadsheet into a DataFrame
df = pd.DataFrame(worksheet.get_all_records())

# Preprocess function
def preprocess_text(text):
    if isinstance(text, str):
        text = text.lower()
        text = re.sub(r'[^a-z\s]', '', text)  # Remove punctuation, numbers, symbols
        words = text.split()
        stop_words = set(stopwords.words('english'))
        words = [word for word in words if word not in stop_words]  # Fixed this line
        return ' '.join(words)
    return ""

# Apply preprocessing
df['preprocessed_text'] = df['Sentence'].apply(preprocess_text)

# Create new Google Sheet and upload
new_sheet_name = 'Preprocessed Sentiment Data'
sh = gc.create(new_sheet_name)
worksheet = sh.sheet1
set_with_dataframe(worksheet, df)

# Share the sheet with your email
your_email = 'najiakhan.se@gmail.com'  # Updated with your Gmail
sh.share(your_email, perm_type='user', role='writer')

# Output the link to the spreadsheet
print("✅ Sheet created and shared!")
print(f"🔗 Open your sheet: https://docs.google.com/spreadsheets/d/{sh.id}")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


✅ Sheet created and shared!
🔗 Open your sheet: https://docs.google.com/spreadsheets/d/1j8yTD-W5-mJV5GpCgSAKA8ch3LOfAz1eV8RQ8HausQU


# Extract Word-Level Sentiment Data from Preprocessed Text

In [7]:
# STEP 1: Load the sheet into df
spreadsheet_name = ' sentiment_spreadsheet'  # Updated name to 'sentiment_spreadsheet'
spreadsheet = gc.open(spreadsheet_name)
worksheet = spreadsheet.sheet1
df = pd.DataFrame(worksheet.get_all_records())

# STEP 2: Preprocess the 'Sentence' column
def preprocess_text(text):
    if isinstance(text, str):
        text = text.lower()
        text = re.sub(r'[^a-z\s]', '', text)
        words = text.split()
        stop_words = set(stopwords.words('english'))
        words = [word for word in words if word not in stop_words]
        return ' '.join(words)
    return ""

df['preprocessed_text'] = df['Sentence'].apply(preprocess_text)

# STEP 3: Split the cleaned text into words and attach sentiment
word_rows = []
for index, row in df.iterrows():
    sentiment = row['Sentiment']
    text = row['preprocessed_text']
    words = text.split()
    for word in words:
        word_rows.append({'Word': word, 'Sentiment': sentiment})

# STEP 4: Upload word-level data to a new Google Sheet
word_df = pd.DataFrame(word_rows)

word_sh = gc.create('Word-Level Sentiment from Preprocessed')
word_ws = word_sh.sheet1
set_with_dataframe(word_ws, word_df)

# STEP 5: Share the sheet
your_email = 'najiakhan.se@gmail.com'  # Updated to your email
word_sh.share(your_email, perm_type='user', role='writer')

# STEP 6: Output link
print("✅ Word-level sentiment sheet created and shared!")
print(f"🔗 View it: https://docs.google.com/spreadsheets/d/{word_sh.id}")


✅ Word-level sentiment sheet created and shared!
🔗 View it: https://docs.google.com/spreadsheets/d/1VsxUB_x2n1Ed7hfOXzrH8pHhTipqhr9y47CvTYQTFI0


# Apply Preprocessing

In [8]:
# 🧼 Apply cleaning to text column
df['cleaned_text'] = df['Sentence'].apply(preprocess_text)
print(df[['Sentence', 'cleaned_text']].head())

                                          Sentence  \
0  The team did an outstanding job on the project.   
1               I’m so proud of how far I’ve come.   
2        This is the best day I’ve had in a while.   
3            Everything went perfectly as planned.   
4              She has a fantastic sense of humor.   

                        cleaned_text  
0       team outstanding job project  
1              im proud far ive come  
2                       best day ive  
3  everything went perfectly planned  
4              fantastic sense humor  


# Train-Test Split & TF-IDF Vectorization

In [9]:
# Features & Target
X = df['cleaned_text']
y = df['Sentiment']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)


# Model Training

In [10]:
# Train Logistic Regression Model
model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(X_train_tfidf, y_train)


LogisticRegression(class_weight='balanced', max_iter=1000)

# Text Normalization for Cleaning Unicode and Special Characters

In [11]:
import unicodedata

def normalize_text(text):
    if isinstance(text, str):
        text = text.replace("’", "'").replace("‘", "'").replace("“", '"').replace("”", '"')
        text = unicodedata.normalize('NFKD', text)
        return text.encode('ascii', 'ignore').decode('utf-8')
    return text

df['Sentence'] = df['Sentence'].apply(normalize_text)


# training code

In [11]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

# 1. Predict on the training data
y_train_pred = model.predict(X_train_tfidf)

# 2. Create a DataFrame including the original text
results = pd.DataFrame({
    'Text': X_train,       # <- Original text (very helpful!)
    'Actual': y_train,

})

# 3. Save it to CSV
csv_filename = 'train_predictions_with_text.csv'
results.to_csv(csv_filename, index=False)

print(f"File '{csv_filename}' created successfully!")

# 4. Download it if using Colab
try:
    from google.colab import files
    files.download(csv_filename)
except:
    print("Download step is only for Colab or Jupyter. File is saved locally.")


File 'train_predictions_with_text.csv' created successfully!


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# Accuracy improvement

In [12]:
print(df['Sentiment'].value_counts())


Sentiment
Positive    40
Negative    40
Neutral     40
Name: count, dtype: int64


In [13]:
vectorizer = TfidfVectorizer(ngram_range=(1, 3), max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [14]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=10000)  # Increase max features


In [15]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=5000, stop_words='english')


In [16]:
model = LogisticRegression(class_weight='balanced', max_iter=1000, C=1.0)
model.fit(X_train_tfidf, y_train)


LogisticRegression(class_weight='balanced', max_iter=1000)

In [17]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, X_train_tfidf, y_train, cv=5, scoring='accuracy')


array([0.25      , 0.57894737, 0.47368421, 0.52631579, 0.57894737])

In [18]:
# Step 1: Fit the TF-IDF Vectorizer
vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=5000, stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Step 2: Fit the Logistic Regression Model
model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(X_train_tfidf, y_train)  # Fit model on the training data

# Step 3: After fitting the model and vectorizer, you can access the coefficients and feature names.
importance = model.coef_[0]  # Coefficients of the trained model
feature_names = vectorizer.get_feature_names_out()  # Get feature names
feature_importance = sorted(zip(importance, feature_names), reverse=True)

# Print top 10 important features
print(feature_importance[:10])


[(np.float64(0.5935559136935675), 'didnt'), (np.float64(0.47200167253525), 'website'), (np.float64(0.39735942575544375), 'finish'), (np.float64(0.358696735021748), 'boring'), (np.float64(0.32826457591953967), 'worked expected'), (np.float64(0.32826457591953967), 'worked'), (np.float64(0.2998764902506231), 'wouldnt recommend'), (np.float64(0.2998764902506231), 'wouldnt'), (np.float64(0.2998764902506231), 'utter failure'), (np.float64(0.2998764902506231), 'utter')]


In [19]:
importance = model.coef_[0]
feature_names = vectorizer.get_feature_names_out()
feature_importance = sorted(zip(importance, feature_names), reverse=True)
print(feature_importance[:10])  # Print top 10 important features


[(np.float64(0.5935559136935675), 'didnt'), (np.float64(0.47200167253525), 'website'), (np.float64(0.39735942575544375), 'finish'), (np.float64(0.358696735021748), 'boring'), (np.float64(0.32826457591953967), 'worked expected'), (np.float64(0.32826457591953967), 'worked'), (np.float64(0.2998764902506231), 'wouldnt recommend'), (np.float64(0.2998764902506231), 'wouldnt'), (np.float64(0.2998764902506231), 'utter failure'), (np.float64(0.2998764902506231), 'utter')]


In [22]:
X = df['cleaned_text']
y = df['Sentiment']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=5000, stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Train the model
model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(X_train_tfidf, y_train)

# Make predictions
y_pred = model.predict(X_test_tfidf)

# Evaluate the model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.4583333333333333
Classification Report:
               precision    recall  f1-score   support

    Negative       0.43      0.30      0.35        10
     Neutral       0.42      0.83      0.56         6
    Positive       0.60      0.38      0.46         8

    accuracy                           0.46        24
   macro avg       0.48      0.50      0.46        24
weighted avg       0.48      0.46      0.44        24

Confusion Matrix:
 [[3 5 2]
 [1 5 0]
 [3 2 3]]


In [23]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 45.83%


In [24]:
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)


Confusion Matrix:
[[3 5 2]
 [1 5 0]
 [3 2 3]]
Classification Report:
              precision    recall  f1-score   support

    Negative       0.43      0.30      0.35        10
     Neutral       0.42      0.83      0.56         6
    Positive       0.60      0.38      0.46         8

    accuracy                           0.46        24
   macro avg       0.48      0.50      0.46        24
weighted avg       0.48      0.46      0.44        24



In [25]:
misclassified = X_test[y_test != y_pred]
print("Misclassified Examples:")
print(misclassified)


Misclassified Examples:
44        always finds something complain
47       app keeps crashing every minutes
4                   fantastic sense humor
55            worst hotel ive ever stayed
26                      staff went beyond
64                  delivery delayed week
73                wasted hours trying fix
10    received excellent customer service
40              product broke one day use
62                       concert disaster
36                        helped one else
88                     train arrived time
31                     room cozy relaxing
Name: cleaned_text, dtype: object


In [26]:
# Check unique values in the 'Sentiment' column to identify the unexpected class
print(df['Sentiment'].unique())


['Positive' 'Negative' 'Neutral']


In [21]:
# Remove rows where the 'Sentiment' is an empty string
df = df[df['Sentiment'] != '']


# testing

In [27]:
import pandas as pd

# Create a DataFrame with the actual text, actual labels, and predicted labels
output_df = pd.DataFrame({
    'Text': X_test,               # Original text
    'Actual Sentiment': y_test,   # Actual labels
    'Predicted Sentiment': y_pred # Predicted labels
})

# Save it to a CSV
output_df.to_csv('model_output.csv', index=False)

# Optionally, download the CSV if you're using Colab
try:
    from google.colab import files
    files.download('model_output.csv')
except:
    print("File saved as 'model_output.csv'.")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# predictions

In [28]:
# ✅ Step 1: TF-IDF Vectorization
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(X)

# ✅ Step 2: Train-Test Split (Fixed!)
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

# ✅ Step 3: Train the Model
model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(X_train, y_train)

# ✅ Step 4: Map test data back to raw sentences
# Get the test indices to find original sentences
_, test_indices = train_test_split(df.index, test_size=0.2, random_state=42)
df_test = df.loc[test_indices].reset_index(drop=True)

# ✅ Step 5: Predict only on test data
rows = []
class_labels = model.classes_

for i, row in df_test.iterrows():
    sentence = row['Sentence']
    sentiment = row['Sentiment']
    text = row['cleaned_text']
    words = text.split()

    token_list = []
    confidence_list = []

    for word in words:
        word_tfidf = vectorizer.transform([word])
        if word_tfidf.nnz == 0:
            probs = [0] * len(class_labels)
        else:
            probs = model.predict_proba(word_tfidf)[0]
            probs = [int(p * 100) for p in probs]

        token_list.append(word)
        confidence_list.append(str(probs))

    # Sentence-level prediction
    sentence_tfidf = vectorizer.transform([text])
    sentence_prediction = model.predict(sentence_tfidf)[0]
    sentence_confidence = model.predict_proba(sentence_tfidf)[0]
    sentence_confidence = [int(p * 100) for p in sentence_confidence]

    rows.append({
        'sentence': sentence,
        'sentiment': sentiment,
        'prediction': sentence_prediction,
        'token': token_list,
        'confidence (positive, negative, neutral)': confidence_list,
        'confidence (sentence)': str(sentence_confidence)
    })

# ✅ Step 6: Save and Download
results_df = pd.DataFrame(rows)
results_df.to_csv("predictions_on_testing_data.csv", index=False)
files.download("predictions_on_testing_data.csv")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [31]:

import pandas as pd
df = pd.read_csv("predictions_on_testing_data.csv")
print("Correct predictions:")
for index, row in df.iterrows():
    if row["sentiment"] == row["prediction"]:
        print(f" {row['sentence']}  {row['prediction']}")


Correct predictions:
 The product broke after one day of use.  Negative
 They moved to a new apartment.  Neutral
 That joke made my day.  Positive
 He opened the window.  Neutral
 I am reading a novel.  Neutral
 I posted a photo online.  Neutral
 The team did an outstanding job on the project.  Positive
 The road is under construction.  Neutral
 I didn't enjoy the experience at all.  Negative
 The customer support was rude and unhelpful.  Negative
 I was treated unfairly.  Negative


In [32]:
import pandas as pd
df = pd.read_csv("predictions_on_testing_data.csv")
print("Wrong predictions:")
for index, row in df.iterrows():
    if row["sentiment"] != row["prediction"]:
        print(f" {row['sentence']}  {row['prediction']} (Expected: {row['sentiment']})")


Wrong predictions:
 He always finds something to complain about.  Positive (Expected: Negative)
 The app keeps crashing every few minutes.  Neutral (Expected: Negative)
 She has a fantastic sense of humor.  Neutral (Expected: Positive)
 It was the worst hotel I've ever stayed in.  Positive (Expected: Negative)
 The staff went above and beyond.  Negative (Expected: Positive)
 The delivery was delayed by a week.  Neutral (Expected: Negative)
 I wasted hours trying to fix it.  Neutral (Expected: Negative)
 I received excellent customer service.  Negative (Expected: Positive)
 The concert was a disaster.  Neutral (Expected: Negative)
 This app really improved my productivity.  Negative (Expected: Positive)
 She helped me when no one else did.  Negative (Expected: Positive)
 The train arrived on time.  Negative (Expected: Neutral)
 This room is so cozy and relaxing.  Neutral (Expected: Positive)


In [33]:
from sklearn.ensemble import RandomForestClassifier  # example model
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import joblib

# Example training
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Save the model
joblib.dump(model, 'sentiment_model.joblib')


['sentiment_model.joblib']

In [34]:
import pandas as pd
import ast  # String ko list mein badalne ke liye

# CSV load karo
df = pd.read_csv("predictions_on_testing_data.csv")

# Har row ke liye confidence list ko evaluate karo (string → list)
df["confidence (sentence)"] = df["confidence (sentence)"].apply(ast.literal_eval)

# Har sentence ka average nikaalo
df["average_confidence"] = df["confidence (sentence)"].apply(lambda x: sum(x)/len(x))

# Show karo sentence ke sath uska average
for index, row in df.iterrows():
    print(f"📝 {row['sentence']}\n🔍 Confidence: {row['confidence (sentence)']} → 📊 Average: {row['average_confidence']:.2f}\n")


📝 He always finds something to complain about.
🔍 Confidence: [30, 32, 36] → 📊 Average: 32.67

📝 The app keeps crashing every few minutes.
🔍 Confidence: [32, 34, 32] → 📊 Average: 32.67

📝 She has a fantastic sense of humor.
🔍 Confidence: [32, 34, 32] → 📊 Average: 32.67

📝 It was the worst hotel I've ever stayed in.
🔍 Confidence: [32, 29, 37] → 📊 Average: 32.67

📝 The staff went above and beyond.
🔍 Confidence: [39, 31, 29] → 📊 Average: 33.00

📝 The delivery was delayed by a week.
🔍 Confidence: [32, 34, 32] → 📊 Average: 32.67

📝 I wasted hours trying to fix it.
🔍 Confidence: [32, 34, 32] → 📊 Average: 32.67

📝 I received excellent customer service.
🔍 Confidence: [35, 31, 32] → 📊 Average: 32.67

📝 The product broke after one day of use.
🔍 Confidence: [40, 28, 31] → 📊 Average: 33.00

📝 They moved to a new apartment.
🔍 Confidence: [30, 38, 30] → 📊 Average: 32.67

📝 That joke made my day.
🔍 Confidence: [34, 30, 35] → 📊 Average: 33.00

📝 The concert was a disaster.
🔍 Confidence: [32, 34, 32] → 